### ISSUE TITLE
DataLoader failure

### ISSUE THREAD

**Issue by broberson** [goldcaddy77/warthog-starter#24]
You can see this using the heroku instance: https://warthog-starter.herokuapp.com/graphql

This query works fine, returns the users and the posts, as you'd expect:

```graphql
{
  posts {
    title
  }
  users {
    email
  }
}
```

as does this one, showing that one-to-many relations are working with the DataLoader:

```graphql
{
  users {
    email
    posts {
      title
    }
  }
}
```

but this one just breaks, giving the error "Cannot return null for non-nullable field Post.user."

```graphql
{
  posts {
    title
    user {
      email
    }
  }
}
```

[This example](https://github.com/goldcaddy77/warthog/tree/master/examples/3-one-to-many-relationship) in the warthog repository works just fine. Maybe this starter repository is a little stale?

**Comment by goldcaddy77** [comment]
Good catch. Will look into this over the weekend.

**Comment by goldcaddy77** [comment]
@broberson - I figured out the issue.  I put a performance fix in where I would only ask postgres for the specific fields that the user asks for.  In doing so, if the user doesn't ask for `id`, then the dataloader has no way to fetch the associated records.

Try:

```
{
  posts {
    id
    title
    user {
      email
    }
  }
}
```

Just add the `id` as well for now and I'll get a fix in for this ASAP.

**Comment by goldcaddy77** [comment]
@broberson - fixed by bumping to latest version of warthog:  https://github.com/goldcaddy77/warthog-starter/pull/25

Warthog fix: https://github.com/goldcaddy77/warthog/pull/181

**Comment by goldcaddy77** [comment]
![image](https://user-images.githubusercontent.com/573625/62185694-6f161b80-b331-11e9-8248-1982219330c4.png)
