### ISSUE TITLE
Mark repository as template

### ISSUE THREAD

**Issue by GrayStrider** [goldcaddy77/warthog-starter#42]
In settings, for easier bootstrapping

**Comment by goldcaddy77** [comment]
Hey, can you elaborate? Do you mean change the file extension or file name?

**Comment by GrayStrider** [comment]
`Settings` -> `Options`
![image](https://user-images.githubusercontent.com/43771776/78731611-e9507280-798b-11ea-9675-5d9b3def6852.png)

**Comment by GrayStrider** [comment]
![image](https://user-images.githubusercontent.com/43771776/78731642-fcfbd900-798b-11ea-8480-8022e4a14123.png)

**Comment by goldcaddy77** [comment]
Awesome, good call.  Closing.

![image](https://user-images.githubusercontent.com/573625/78735260-54f8f800-7918-11ea-90e2-74092ba8358a.png)
